//Matheus Xavier Soares - 2142651
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mxsoa
 */
public class Carrinho extends javax.swing.JFrame {
    
    Detalhe det = new Detalhe();
    /**
     * Creates new form TabTecCad
     */
    public Carrinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProd = new javax.swing.JTable();
        btFinCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho de Compras");

        rtTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtTitulo.setText("Lista de Produtos no Carrinho");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço Unitário", "Quantidade"
            }
        ));
        tabProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabProd);

        btFinCompra.setText("Finalizar Compra");
        btFinCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(btFinCompra)
                .addGap(47, 47, 47)
                .addComponent(btSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(rtTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(rtTitulo)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btFinCompra))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void tabProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdMouseClicked
        String nomeComponente = "";
        int posLinha = tabProd.getSelectedRow();
        for (int coluna = 0;coluna < tabProd.getColumnCount();coluna++){
            nomeComponente += tabProd.getModel().getValueAt(posLinha, coluna).toString();
            if(coluna < tabProd.getColumnCount()){
                nomeComponente += "-";
            }
        }
        
        JOptionPane.showMessageDialog(null,"Dados do Produto Inserido: "+nomeComponente,"Dados do Produto",1);
    }//GEN-LAST:event_tabProdMouseClicked

    private void btFinCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinCompraActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Você deseja finalizar a compra?","Finalizar Compra",JOptionPane.YES_NO_CANCEL_OPTION);
                if(opcao == 0){
                    JOptionPane.showMessageDialog(null, "Pedido realizado com sucesso! Aguardando Pagamento...","Pedido Realizado", 1);
                }
    }//GEN-LAST:event_btFinCompraActionPerformed
    public void showProd(BancoProduto bDet){
        this.setVisible(true);
        det = new Detalhe();

        DefaultTableModel modTabProd = new DefaultTableModel();
        
        modTabProd = (DefaultTableModel) tabProd.getModel();
        
        modTabProd.setRowCount(0);
        
        for(int posLin=0;posLin < bDet.getBDDet().size();posLin++){
            det.setCod(bDet.getBDDet().get(posLin).getCod());
            det.setNome(bDet.getBDDet().get(posLin).getNome());
            det.setDescricao(bDet.getBDDet().get(posLin).getDescricao());
            det.setPreco(bDet.getBDDet().get(posLin).getPreco());
            det.setQuantidade(bDet.getBDDet().get(posLin).getQuantidade());
            modTabProd.insertRow(posLin, new Object[]{det.getCod(),det.getNome(),det.getDescricao(),det.getPreco(),det.getQuantidade()});
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinCompra;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JTable tabProd;
    // End of variables declaration//GEN-END:variables
}
